spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: ems
    password: 123
    virtual-host: /ems
    # 开启确认模式，publisher -> exchange 无论成功与否执行回调函数，通过 true(成功)/false(失败) 标识
    publisher-confirms: true
    # 开启返回模式，exchange -> queue 失败返回
    publisher-returns: true
    # 设置消费者消息接收手动确认
    listener:
      simple:
        acknowledge-mode: manual

server:
  port: 80